function Get-AuthentikSigningKeypair {
    <#
    .SYNOPSIS
        Finds the seeded signing certificate, or generates it

    .DESCRIPTION
        A SAML provider that signs its responses needs a certificate keypair, and the seed
        must not borrow one that belongs to the instance: signing lab assertions with a real
        key is the wrong direction for a test tool, and teardown could never remove it. So the
        seed owns one, named with the prefix and generated by Authentik itself as a
        self-signed certificate, and reuses it on every run until teardown deletes it.

        The private key never leaves the instance: the generate endpoint returns the keypair's
        metadata and the module reads only its primary key.

    .PARAMETER Connection
        The connection to use. Defaults to the active one.

    .OUTPUTS
        System.String. The keypair's primary key.

    .EXAMPLE
        PS> $kp = Get-AuthentikSigningKeypair

        DESCRIPTION: Returns the seeded keypair, generating it on the first call
        OUTPUT: A UUID
        USE CASE: The signing_kp of the seeded SAML provider

    .NOTES
        Author: Jeffrey Stuhr
        Blog: https://www.techbyjeff.net
        LinkedIn: https://www.linkedin.com/in/jeffrey-stuhr-034214aa/
    #>

    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter()]
        [hashtable]$Connection
    )

    if (-not $Connection) { $Connection = Get-AuthentikConnection }
    $marker = Get-AuthentikSeedMarker -Connection $Connection
    $name = '{0}SAML Signing' -f $marker.Prefix

    $existing = @(Get-AuthentikSeededObject -Type Certificates -Connection $Connection | Where-Object { $_.name -eq $name })
    if ($existing.Count -gt 0) {
        Write-Verbose "Reusing signing keypair $name"
        return [string]$existing[0].pk
    }

    $keypair = Invoke-AuthentikRequest -Method POST -Path '/crypto/certificatekeypairs/generate/' -Connection $Connection -Body @{
        common_name   = $name
        validity_days = 365
    }
    Write-Verbose "Generated signing keypair $name"
    return [string]$keypair.pk
}
