#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '6.1.0' }

<#
    The seed data is the specification of what the provider builds, and the shapes in it are
    deliberate: a nesting chain three deep, a contractor population outside the chain, a
    disabled user who keeps memberships, names with accents, a policy that names a seeded
    group. Each of those is a case a report has to survive, and each is lost silently if a
    row is edited carelessly - a user placed in a group that does not exist is created fine
    and is simply not where the test expected. These tests read the CSVs directly, with no
    module and no mocks, and pin the shapes and the references between files.

    The users and groups have two tiers. Core is the hand-designed rows above; Bulk is the AD
    provider's directory mapped across, so the same people exist in three labs and a report
    that works on ten users is proved on three hundred. The bulk is generated by
    Tools\New-AuthentikTestSeedData.ps1 and never edited by hand, and the last test here
    regenerates it and fails if the committed files have drifted from what the tool writes.
#>

BeforeAll {
    $script:DataPath = Join-Path (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))) 'Providers\Authentik\Data'
    $script:Groups = @(Import-Csv -Path (Join-Path $script:DataPath 'AuthentikGroups.csv') -Encoding UTF8)
    $script:Users = @(Import-Csv -Path (Join-Path $script:DataPath 'AuthentikUsers.csv') -Encoding UTF8)
    $script:Applications = @(Import-Csv -Path (Join-Path $script:DataPath 'AuthentikApplications.csv') -Encoding UTF8)
    $script:Policies = @(Import-Csv -Path (Join-Path $script:DataPath 'AuthentikPolicies.csv') -Encoding UTF8)
    $script:Rules = @(Import-Csv -Path (Join-Path $script:DataPath 'AuthentikNotificationRules.csv') -Encoding UTF8)
}

Describe 'Authentik seed data' -Tag 'Unit', 'Contract' {

    Context 'Counts' {
        It 'holds the designed number of core rows per file' {
            @($script:Groups | Where-Object Tier -eq 'Core').Count | Should-Be 9
            @($script:Users | Where-Object Tier -eq 'Core').Count | Should-Be 10
            $script:Applications.Count | Should-Be 6
            $script:Policies.Count | Should-Be 3
            $script:Rules.Count | Should-Be 2
        }

        It 'carries the AD provider across as the bulk tier, at parity with Entra' {
            # The Entra provider maps the same 296 people and 90 groups; one AD group shares
            # its display name with a core group and is dropped, because Authentik group
            # names are unique.
            @($script:Users | Where-Object Tier -eq 'Bulk').Count | Should-Be 296
            @($script:Groups | Where-Object Tier -eq 'Bulk').Count | Should-Be 89
        }

        It 'puts every user and group in exactly one tier' {
            @($script:Users | Where-Object { $_.Tier -notin 'Core', 'Bulk' }) | Should-BeCollection -Count 0
            @($script:Groups | Where-Object { $_.Tier -notin 'Core', 'Bulk' }) | Should-BeCollection -Count 0
        }
    }

    Context 'Groups' {
        BeforeAll {
            $script:ParentsOf = @{}
            foreach ($g in $script:Groups) { $script:ParentsOf[$g.Name] = @($g.Parent -split ';' | Where-Object { $_ }) }
            $script:DepthOf = {
                param($key)
                $d = 0; $frontier = @($script:ParentsOf[$key])
                while ($frontier.Count -gt 0 -and $d -lt 20) { $d++; $frontier = @($frontier | ForEach-Object { if ($script:ParentsOf.ContainsKey($_)) { $script:ParentsOf[$_] } }) }
                $d
            }
        }

        It 'has unique keys and unique display names' {
            @($script:Groups.Name | Sort-Object -Unique).Count | Should-Be $script:Groups.Count
            @($script:Groups.DisplayName | Sort-Object -Unique).Count | Should-Be $script:Groups.Count
        }

        It 'names only parents that exist' {
            $unknown = @($script:Groups | ForEach-Object { $script:ParentsOf[$_.Name] } | Where-Object { $script:Groups.Name -notcontains $_ })
            $unknown | Should-BeCollection -Count 0
        }

        It 'nests three deep in the core chain' {
            (& $script:DepthOf 'Team-Platform') | Should-Be 2
        }

        It 'brings AD nesting across, including a group with more than one parent' {
            # Authentik groups take a list of parents, so AD's graph is reproduced rather than
            # flattened, and the seed has to hand a child every parent pk.
            $multi = @($script:Groups | Where-Object { $script:ParentsOf[$_.Name].Count -gt 1 })
            $multi.Count | Should-BeGreaterThan 0
            (@($script:Groups | ForEach-Object { & $script:DepthOf $_.Name } | Measure-Object -Maximum).Maximum) | Should-BeGreaterThan 2
        }

        It 'never nests a bulk group under a core one, or a core group under a bulk one' {
            $tierOf = @{}
            foreach ($g in $script:Groups) { $tierOf[$g.Name] = $g.Tier }
            $crossed = @($script:Groups | Where-Object { $row = $_; @($script:ParentsOf[$row.Name] | Where-Object { $tierOf[$_] -ne $row.Tier }).Count -gt 0 })
            $crossed | Should-BeCollection -Count 0
        }

        It 'has a non-ASCII display name in each tier' {
            @($script:Groups | Where-Object { $_.Tier -eq 'Core' -and $_.DisplayName -match '[^\x00-\x7F]' }) | Should-BeCollection -Count 1
            @($script:Groups | Where-Object { $_.Tier -eq 'Bulk' -and $_.DisplayName -match '[^\x00-\x7F]' }).Count | Should-BeGreaterThan 0
        }

        It 'has exactly one group nobody is a member of, and it is the designed one' {
            $members = @($script:Users.Groups -split ';' | Where-Object { $_ } | Sort-Object -Unique)
            @($script:Groups | Where-Object { $members -notcontains $_.Name }).Name | Should-BeCollection @('Empty-Hold')
        }
    }

    Context 'Users' {
        It 'has unique usernames' {
            @($script:Users.Username | Sort-Object -Unique).Count | Should-Be $script:Users.Count
        }

        It 'gives every human at least one group' {
            @($script:Users | Where-Object { $_.Type -ne 'service_account' -and -not $_.Groups }) | Should-BeCollection -Count 0
        }

        It 'keeps the bulk out of the core policy targets' {
            # The payroll policy admits one group and the seed promises exactly one user is in
            # it. A bulk row joining Dept-Finance would silently change what the policy proves.
            @($script:Users | Where-Object { ($_.Groups -split ';') -contains 'Dept-Finance' }).Username | Should-BeCollection @('praghunathan')
        }

        It 'places every contractor outside the staff chain' {
            $contractors = @($script:Users | Where-Object LabIsContractor -eq 'TRUE')
            $contractors.Count | Should-BeGreaterThan 2
            @($contractors | Where-Object { ($_.Groups -split ';') -contains 'All-Staff' }) | Should-BeCollection -Count 0
            @($contractors | Where-Object { ($_.Groups -split ';') -notcontains 'Contractors' }) | Should-BeCollection -Count 0
        }

        It 'places every user only in groups that exist' {
            $unknown = @($script:Users | ForEach-Object { $_.Groups -split ';' } | Where-Object { $_ -and ($script:Groups.Name -notcontains $_) })
            $unknown | Should-BeCollection -Count 0
        }

        It 'names a manager who exists, or none' {
            $unknown = @($script:Users | Where-Object { $_.Manager -and ($script:Users.Username -notcontains $_.Manager) })
            $unknown | Should-BeCollection -Count 0
        }

        It 'uses only the user types Authentik defines' {
            $bad = @($script:Users | Where-Object { $_.Type -notin 'internal', 'external', 'service_account', 'internal_service_account' })
            $bad | Should-BeCollection -Count 0
        }

        It 'carries booleans that parse' {
            foreach ($u in $script:Users) {
                $u.IsActive | Should-MatchString '^(TRUE|FALSE)$'
                $u.LabIsContractor | Should-MatchString '^(TRUE|FALSE)$'
            }
        }

        It 'has exactly one service account among the humans' {
            @($script:Users | Where-Object Type -eq 'service_account') | Should-BeCollection -Count 1
        }

        It 'has a disabled user who still holds memberships' {
            $disabled = @($script:Users | Where-Object { $_.IsActive -eq 'FALSE' -and $_.Groups })
            $disabled.Count | Should-BeGreaterThan 0
        }

        It 'marks every external user as a contractor and no internal one' {
            @($script:Users | Where-Object { $_.Type -eq 'external' -and $_.LabIsContractor -ne 'TRUE' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.Type -eq 'internal' -and $_.LabIsContractor -eq 'TRUE' }) | Should-BeCollection -Count 0
        }

        It 'keeps the accented names intact through a UTF-8 read' {
            @($script:Users | Where-Object { $_.Name -match '[^\x00-\x7F]' }).Count | Should-BeGreaterThan 2
        }
    }

    Context 'Applications' {
        It 'uses only the provider types the seed can create' {
            @($script:Applications | Where-Object { $_.ProviderType -notin 'OAuth2', 'Proxy', 'None' }) | Should-BeCollection -Count 0
        }

        It 'gives every OAuth2 client a type and a redirect' {
            foreach ($a in ($script:Applications | Where-Object ProviderType -eq 'OAuth2')) {
                $a.ClientType | Should-MatchString '^(confidential|public)$'
                $a.RedirectUri | Should-MatchString '^https://'
            }
        }

        It 'gives every proxy an external host and an internal one' {
            # Authentik refuses a proxy provider with no internal host unless forward auth is
            # on, so a row without one is created fine in a mock and fails against an instance.
            foreach ($a in ($script:Applications | Where-Object ProviderType -eq 'Proxy')) {
                $a.ExternalHost | Should-MatchString '^https://'
                $a.InternalHost | Should-MatchString '^https?://'
            }
        }

        It 'writes every URL against the seed domain so it can be substituted' {
            $urls = @($script:Applications | ForEach-Object { $_.LaunchUrl; $_.ExternalHost; $_.RedirectUri } | Where-Object { $_ })
            @($urls | Where-Object { $_ -notmatch 'authentiklab\.example\.com' }) | Should-BeCollection -Count 0
        }

        It 'has one application with no provider and one that is hidden' {
            @($script:Applications | Where-Object ProviderType -eq 'None') | Should-BeCollection -Count 1
            @($script:Applications | Where-Object Hidden -eq 'TRUE') | Should-BeCollection -Count 1
        }

        It 'has unique slugs' {
            @($script:Applications.Slug | Sort-Object -Unique).Count | Should-Be $script:Applications.Count
        }
    }

    Context 'Policies' {
        It 'targets an application slug that exists' {
            @($script:Policies | Where-Object { $script:Applications.Slug -notcontains $_.Target }) | Should-BeCollection -Count 0
        }

        It 'refers to a seeded group by placeholder, never by a literal prefix' {
            @($script:Policies | Where-Object { $_.Expression -match 'ZZ-TEST' }) | Should-BeCollection -Count 0
            @($script:Policies | Where-Object { $_.Expression -match '\{prefix\}' }).Count | Should-BeGreaterThan 0
        }

        It 'has one disabled binding' {
            @($script:Policies | Where-Object Enabled -eq 'FALSE') | Should-BeCollection -Count 1
        }
    }

    Context 'Notification rules' {
        It 'uses only the severities Authentik defines' {
            @($script:Rules | Where-Object { $_.Severity -notin 'notice', 'warning', 'alert' }) | Should-BeCollection -Count 0
        }

        It 'points every webhook at the example domain' {
            @($script:Rules | Where-Object { $_.WebhookUrl -notmatch '^https://example\.com/' }) | Should-BeCollection -Count 0
        }
    }

    Context 'Regeneration' {
        It 'regenerates the committed users and groups byte for byte' {
            # The bulk is generated, and a hand edit to it is lost the next time the tool
            # runs. Regenerating into a temporary folder and comparing bytes catches both a
            # hand edit and a tool change that was not committed with its output.
            $tool = Join-Path (Split-Path -Parent $script:DataPath) 'Tools\New-AuthentikTestSeedData.ps1'
            $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("authentik-seed-" + [Guid]::NewGuid().ToString('N'))
            $null = New-Item -ItemType Directory -Path $temp -Force
            try {
                $null = & $tool -OutputPath $temp
                foreach ($name in 'AuthentikUsers.csv', 'AuthentikGroups.csv') {
                    $expected = [System.IO.File]::ReadAllBytes((Join-Path $temp $name))
                    $actual = [System.IO.File]::ReadAllBytes((Join-Path $script:DataPath $name))
                    [Convert]::ToBase64String($actual) | Should-Be ([Convert]::ToBase64String($expected))
                }
            }
            finally {
                Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue
            }
        }
    }
}
