#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '6.1.0' }

<#
    The seed data is the specification of what the provider builds, and the shapes in it are
    deliberate: a nesting chain three deep with a non-POSIX group in the middle, a contractor
    population outside the chain, a disabled user who keeps memberships and a sudo rule, a
    staged hire and a preserved leaver, a contractor whose principal expired but whose account
    was never disabled, an authentication type that demands a token nobody enrolled, an
    allow-everything HBAC rule that is switched off, vim under sudo without a password. Each of
    those is a case a report has to survive, and each is lost silently if a row is edited
    carelessly - a user placed in a group that does not exist is created fine and is simply
    not where the test expected. These tests read the CSVs directly, with no module and no
    mocks, and pin the shapes and the references between files.

    They also pin what the data must never say. FreeIPA ships objects that every host in a
    realm depends on - admins, ipausers, allow_all, global_policy, the default trust view -
    and a row that named one of them would have the seed write to it. A reference to a stock
    object is allowed only where the seed can use it without changing it, and only by an
    explicit builtin: marker, so that the test can list exactly which ones.

    The users, groups, hosts and host groups have two tiers. Core is the hand-designed rows
    above; Bulk is the AD provider's directory mapped across, so the same people and machines
    exist in four labs and a report that works on a dozen users is proved on three hundred.
    The bulk is generated by Tools\New-FreeIPATestSeedData.ps1 and never edited by hand, and
    the last test here regenerates it and fails if the committed files have drifted from
    what the tool writes.
#>

BeforeAll {
    $script:DataPath = Join-Path (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))) 'Providers\FreeIPA\Data'
    $read = { param($name) @(Import-Csv -Path (Join-Path $script:DataPath "FreeIPA$name.csv") -Encoding UTF8) }
    $script:Users = & $read 'Users'
    $script:Groups = & $read 'Groups'
    $script:Hosts = & $read 'Hosts'
    $script:Hostgroups = & $read 'Hostgroups'
    $script:Netgroups = & $read 'Netgroups'
    $script:HbacServices = & $read 'HbacServices'
    $script:HbacRules = & $read 'HbacRules'
    $script:SudoCommands = & $read 'SudoCommands'
    $script:SudoRules = & $read 'SudoRules'
    $script:Permissions = & $read 'Permissions'
    $script:Privileges = & $read 'Privileges'
    $script:Roles = & $read 'Roles'
    $script:PasswordPolicies = & $read 'PasswordPolicies'
    $script:Services = & $read 'Services'
    $script:IdViews = & $read 'IdViews'
    $script:IdOverrides = & $read 'IdOverrides'
    $script:OtpTokens = & $read 'OtpTokens'
    $script:AutomemberRules = & $read 'AutomemberRules'
    $script:Automount = & $read 'Automount'
    $script:SelinuxUserMaps = & $read 'SelinuxUserMaps'
    $script:CertMapRules = & $read 'CertMapRules'
    $script:ServiceDelegation = & $read 'ServiceDelegation'
    $script:CaAcls = & $read 'CaAcls'
    $script:Certificates = & $read 'Certificates'
    $script:DnsRecords = & $read 'DnsRecords'
    $script:IdentityProviders = & $read 'IdentityProviders'

    # The one name pattern FreeIPA applies to users, groups, host groups and netgroups, and
    # the length limit an instance applies to a login out of the box.
    $script:NamePattern = '^[a-z0-9_.][a-z0-9_.-]*[a-z0-9_.$-]?$'

    # Names FreeIPA creates at install and every enrolled host depends on. Naming one in a
    # seeded row would have the seed create, modify or delete it.
    $script:StockNames = @(
        'admin', 'admins', 'ipausers', 'editors', 'trust admins', 'ipaservers', 'allow_all',
        'allow_systemd-user', 'global_policy', 'default trust view', 'default', 'auto.master',
        'ipa-http-delegation', 'ipa-http-delegation-targets', 'ipa-ldap-delegation-targets',
        'ipa-cifs-delegation-targets', 'hosts_services_caipaservicecert'
    )

    # Stock objects a seeded row may reference through builtin:, because attaching to them
    # changes nothing about them: PAM service names, and one read-only privilege.
    $script:AllowedBuiltinServices = @('sshd', 'login', 'sudo', 'sudo-i', 'su', 'su-l', 'gdm', 'gdm-password', 'crond', 'systemd-user')
    $script:AllowedBuiltinPrivileges = @('Password Policy Readers')
    # The profiles a realm ships that the seed may request through, and the one CA.
    $script:AllowedBuiltinProfiles = @('IECUserRoles', 'caIPAserviceCert')
    $script:AllowedBuiltinCas = @('ipa')

    $script:Split = { param($value) @([string]$value -split ';' | Where-Object { $_ }) }
    $script:Seeded = { param($value) @(& $script:Split $value | Where-Object { $_ -notlike 'builtin:*' }) }
    $script:Builtin = { param($value) @(& $script:Split $value | Where-Object { $_ -like 'builtin:*' } | ForEach-Object { $_.Substring(8) }) }
}

Describe 'FreeIPA seed data' -Tag 'Unit', 'Contract' {

    Context 'Counts' {
        It 'holds the designed number of core rows per file' {
            @($script:Users | Where-Object Tier -eq 'Core').Count | Should-Be 12
            @($script:Groups | Where-Object Tier -eq 'Core').Count | Should-Be 12
            @($script:Hosts | Where-Object Tier -eq 'Core').Count | Should-Be 8
            @($script:Hostgroups | Where-Object Tier -eq 'Core').Count | Should-Be 8
            $script:Netgroups.Count | Should-Be 4
            $script:HbacServices.Count | Should-Be 6
            $script:HbacRules.Count | Should-Be 7
            $script:SudoCommands.Count | Should-Be 12
            $script:SudoRules.Count | Should-Be 7
            $script:Permissions.Count | Should-Be 3
            $script:Privileges.Count | Should-Be 3
            $script:Roles.Count | Should-Be 4
            $script:PasswordPolicies.Count | Should-Be 3
            $script:Services.Count | Should-Be 4
            $script:IdViews.Count | Should-Be 2
            $script:IdOverrides.Count | Should-Be 4
            $script:OtpTokens.Count | Should-Be 4
            $script:AutomemberRules.Count | Should-Be 5
            $script:Automount.Count | Should-Be 9
            $script:SelinuxUserMaps.Count | Should-Be 3
            $script:CertMapRules.Count | Should-Be 3
            $script:ServiceDelegation.Count | Should-Be 3
            $script:CaAcls.Count | Should-Be 4
            $script:Certificates.Count | Should-Be 10
            $script:DnsRecords.Count | Should-Be 11
            $script:IdentityProviders.Count | Should-Be 4
        }

        It 'carries the AD provider across as the bulk tier' {
            # 296 people and 25 service accounts, 90 groups, and the 405 devices that can enrol
            # in an identity domain; phones and printers stay in AD.
            @($script:Users | Where-Object Tier -eq 'Bulk').Count | Should-Be 321
            @($script:Users | Where-Object { $_.Tier -eq 'Bulk' -and $_.Class -eq 'service' }).Count | Should-Be 25
            @($script:Groups | Where-Object Tier -eq 'Bulk').Count | Should-Be 90
            @($script:Hosts | Where-Object Tier -eq 'Bulk').Count | Should-Be 405
            @($script:Hostgroups | Where-Object Tier -eq 'Bulk').Count | Should-Be 22
        }

        It 'puts every tiered row in exactly one tier' {
            foreach ($set in $script:Users, $script:Groups, $script:Hosts, $script:Hostgroups) {
                @($set | Where-Object { $_.Tier -notin 'Core', 'Bulk' }) | Should-BeCollection -Count 0
            }
        }
    }

    Context 'Names' {
        It 'gives every keyed object a name FreeIPA accepts, unique within its file' {
            foreach ($set in @{ Rows = $script:Users; Key = 'Username' }, @{ Rows = $script:Groups; Key = 'Name' }, @{ Rows = $script:Hostgroups; Key = 'Name' },
                @{ Rows = $script:Netgroups; Key = 'Name' }, @{ Rows = $script:HbacServices; Key = 'Name' }, @{ Rows = $script:HbacRules; Key = 'Name' },
                @{ Rows = $script:SudoRules; Key = 'Name' }, @{ Rows = $script:Permissions; Key = 'Name' }, @{ Rows = $script:Privileges; Key = 'Name' },
                @{ Rows = $script:Roles; Key = 'Name' }, @{ Rows = $script:IdViews; Key = 'Name' }, @{ Rows = $script:OtpTokens; Key = 'Id' },
                @{ Rows = $script:SelinuxUserMaps; Key = 'Name' }, @{ Rows = $script:CertMapRules; Key = 'Name' }, @{ Rows = $script:ServiceDelegation; Key = 'Name' },
                @{ Rows = $script:CaAcls; Key = 'Name' }, @{ Rows = $script:Certificates; Key = 'Key' }, @{ Rows = $script:IdentityProviders; Key = 'Name' }) {
                $keys = @($set.Rows | ForEach-Object { $_.($set.Key) })
                @($keys | Sort-Object -Unique).Count | Should-Be $keys.Count
                @($keys | Where-Object { $_ -notmatch $script:NamePattern }) | Should-BeCollection -Count 0
            }
        }

        It 'keeps every login within the length an instance allows, and every host name a DNS label with the prefix on' {
            # Logins are not prefixed; the tag in userclass is what marks them. Hosts are, and
            # zz-test- plus the name has to fit a 63-character label.
            @($script:Users | Where-Object { $_.Username.Length -gt 32 }) | Should-BeCollection -Count 0
            @($script:Hosts.Name | Sort-Object -Unique).Count | Should-Be $script:Hosts.Count
            @($script:Hosts | Where-Object { $_.Name -notmatch '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$' -or $_.Name.Length -gt 55 }) | Should-BeCollection -Count 0
        }

        It 'never names an object FreeIPA created at install' {
            $keys = @($script:Users.Username) + @($script:Groups.Name) + @($script:Hostgroups.Name) + @($script:Netgroups.Name) +
            @($script:HbacRules.Name) + @($script:SudoRules.Name) + @($script:Roles.Name) + @($script:Privileges.Name) +
            @($script:Permissions.Name) + @($script:IdViews.Name) + @($script:PasswordPolicies.Group) + @($script:Automount.Location) +
            @($script:ServiceDelegation.Name) + @($script:AutomemberRules.Target) + @($script:CaAcls.Name)
            @($keys | Where-Object { $script:StockNames -contains $_.ToLowerInvariant() }) | Should-BeCollection -Count 0
        }

        It 'never carries the prefix or the tag as a literal, only as a placeholder' {
            # The prefix is applied at creation time from the connection, and the tag with it.
            # A literal in the data would survive a prefix change and stop matching.
            foreach ($file in (Get-ChildItem -Path $script:DataPath -Filter *.csv)) {
                $text = [System.IO.File]::ReadAllText($file.FullName)
                $text | Should-NotMatchString '(?i)zz-test'
                @([regex]::Matches($text, '\{[a-z]+\}') | ForEach-Object { $_.Value } | Sort-Object -Unique | Where-Object { $_ -notin '{prefix}', '{tag}', '{realm}', '{zone}' }) | Should-BeCollection -Count 0
            }
        }

        It 'never gives a netgroup the name of a host group' {
            # FreeIPA creates a managed netgroup for every host group, of the same name, and
            # refuses a netgroup that would collide with one.
            @($script:Netgroups | Where-Object { $script:Hostgroups.Name -contains $_.Name }) | Should-BeCollection -Count 0
        }
    }

    Context 'Groups' {
        BeforeAll {
            $script:ParentsOf = @{}
            foreach ($g in $script:Groups) { $script:ParentsOf[$g.Name] = @(& $script:Split $g.Parent) }
            $script:DepthOf = {
                param($key)
                $d = 0; $frontier = @($script:ParentsOf[$key])
                while ($frontier.Count -gt 0 -and $d -lt 20) { $d++; $frontier = @($frontier | ForEach-Object { if ($script:ParentsOf.ContainsKey($_)) { $script:ParentsOf[$_] } }) }
                $d
            }
        }

        It 'names only parents that exist, and uses only the group types FreeIPA has' {
            @($script:Groups | ForEach-Object { $script:ParentsOf[$_.Name] } | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
            @($script:Groups | Where-Object { $_.Type -notin 'posix', 'nonposix', 'external' }) | Should-BeCollection -Count 0
        }

        It 'nests three deep in the core chain, with a non-POSIX group in the middle' {
            (& $script:DepthOf 'team-platform') | Should-Be 2
            ($script:Groups | Where-Object Name -eq 'team-platform').Type | Should-Be 'nonposix'
            ($script:Groups | Where-Object Name -eq 'dept-engineering').Type | Should-Be 'posix'
        }

        It 'brings AD nesting across, including a group with more than one parent' {
            @($script:Groups | Where-Object { $script:ParentsOf[$_.Name].Count -gt 1 }).Count | Should-BeGreaterThan 0
            (@($script:Groups | ForEach-Object { & $script:DepthOf $_.Name } | Measure-Object -Maximum).Maximum) | Should-BeGreaterThan 2
        }

        It 'never nests a bulk group under a core one, or a core group under a bulk one' {
            $tierOf = @{}
            foreach ($g in $script:Groups) { $tierOf[$g.Name] = $g.Tier }
            @($script:Groups | Where-Object { $row = $_; @($script:ParentsOf[$row.Name] | Where-Object { $tierOf[$_] -ne $row.Tier }).Count -gt 0 }) | Should-BeCollection -Count 0
        }

        It 'has one external group, nested in a POSIX group, and neither holds a user' {
            # An external group holds trusted-domain SIDs, which the seed cannot supply, and
            # the POSIX wrapper is how a trust hands those a GID. Both are empty on purpose.
            $external = @($script:Groups | Where-Object Type -eq 'external')
            $external.Count | Should-Be 1
            ($script:Groups | Where-Object Name -eq $external[0].Parent).Type | Should-Be 'posix'
            $members = @($script:Users | ForEach-Object { & $script:Split $_.Groups } | Sort-Object -Unique)
            @($script:Groups | Where-Object { $members -notcontains $_.Name } | ForEach-Object { $_.Name } | Sort-Object) | Should-BeCollection @('empty-hold', 'ext-partners', 'ext-partners-posix')
        }

        It 'has a non-ASCII description in each tier' {
            @($script:Groups | Where-Object { $_.Tier -eq 'Core' -and $_.Description -match '[^\x00-\x7F]' }).Count | Should-BeGreaterThan 0
            @($script:Groups | Where-Object { $_.Tier -eq 'Bulk' -and $_.Description -match '[^\x00-\x7F]' }).Count | Should-BeGreaterThan 0
        }

        It 'makes the access lists non-POSIX and the organisation POSIX' {
            @($script:Groups | Where-Object { $_.Category -in 'Application Access', 'Resource Access', 'Device Access' -and $_.Type -ne 'nonposix' }) | Should-BeCollection -Count 0
            @($script:Groups | Where-Object { $_.Category -in 'Department', 'Departmental', 'Geographic', 'Organisation' -and $_.Type -ne 'posix' }) | Should-BeCollection -Count 0
        }
    }

    Context 'Users' {
        It 'places every user only in groups that exist, and names a manager who exists or none' {
            @($script:Users | ForEach-Object { & $script:Split $_.Groups } | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.Manager -and ($script:Users.Username -notcontains $_.Manager) }) | Should-BeCollection -Count 0
        }

        It 'uses only the lifecycle states, classes and authentication types FreeIPA has' {
            @($script:Users | Where-Object { $_.Lifecycle -notin 'Active', 'Disabled', 'Staged', 'Preserved' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.Class -notin 'employee', 'contractor', 'intern', 'service' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.UserAuthType -and $_.UserAuthType -notin 'password', 'radius', 'otp', 'pkinit', 'hardened', 'idp', 'passkey' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.PasswordState -notin 'None', 'MustChange', 'Current' }) | Should-BeCollection -Count 0
            foreach ($u in $script:Users) { $u.NoPrivateGroup | Should-MatchString '^(TRUE|FALSE)$' }
        }

        It 'has one of each lifecycle state beyond Active, and the staged hire holds no membership' {
            # A staged entry cannot be a group member until it is activated, and a preserved
            # one loses every membership when it is preserved; the row keeps what it had.
            @($script:Users | Where-Object Lifecycle -eq 'Staged').Count | Should-Be 1
            @($script:Users | Where-Object Lifecycle -eq 'Preserved').Count | Should-Be 1
            ($script:Users | Where-Object Lifecycle -eq 'Staged').Groups | Should-Be ''
            ($script:Users | Where-Object Lifecycle -eq 'Preserved').Groups | Should-NotBe ''
            @($script:Users | Where-Object { $_.Lifecycle -eq 'Disabled' -and $_.Groups }).Count | Should-BeGreaterThan 0
        }

        It 'gives every active or disabled human at least one group' {
            @($script:Users | Where-Object { $_.Class -ne 'service' -and $_.Lifecycle -in 'Active', 'Disabled' -and -not $_.Groups }) | Should-BeCollection -Count 0
        }

        It 'keeps the class and the employee type in agreement' {
            $expected = @{ employee = 'Employee', 'Full-time'; contractor = @('Contractor'); intern = @('Intern'); service = @('Service') }
            @($script:Users | Where-Object { $expected[$_.Class] -notcontains $_.EmployeeType }) | Should-BeCollection -Count 0
        }

        It 'keeps the bulk out of the core policy targets' {
            # The payroll rule admits one group and the seed promises exactly one user is in
            # it. A bulk row joining dept-finance would silently change what the rule proves.
            @($script:Users | Where-Object { (& $script:Split $_.Groups) -contains 'dept-finance' }).Username | Should-BeCollection @('praghunathan')
        }

        It 'places every contractor outside the staff chain, and every contractor in the group the automember rule fills' {
            $contractors = @($script:Users | Where-Object Class -eq 'contractor')
            $contractors.Count | Should-BeGreaterThan 2
            @($contractors | Where-Object { (& $script:Split $_.Groups) -contains 'all-staff' }) | Should-BeCollection -Count 0
            @($contractors | Where-Object { (& $script:Split $_.Groups) -notcontains 'contractors' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.Class -ne 'contractor' -and (& $script:Split $_.Groups) -contains 'contractors' }) | Should-BeCollection -Count 0
        }

        It 'puts every service account in the service group with no shell, and nothing human beside it' {
            $services = @($script:Users | Where-Object Class -eq 'service')
            $services.Count | Should-Be 26
            @($services | Where-Object { $_.LoginShell -ne '/sbin/nologin' -or (& $script:Split $_.Groups) -notcontains 'svc-accounts' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.Class -ne 'service' -and (& $script:Split $_.Groups) -contains 'svc-accounts' }) | Should-BeCollection -Count 0
        }

        It 'links a radius user to a seeded proxy and an idp user to a seeded provider, and nobody else to either' {
            $proxies = @($script:IdentityProviders | Where-Object Kind -eq 'Radius').Name
            $idps = @($script:IdentityProviders | Where-Object Kind -eq 'Idp').Name
            foreach ($u in $script:Users) {
                if ($u.RadiusProxy) { $proxies | Should-ContainCollection $u.RadiusProxy; $u.UserAuthType | Should-Be 'radius'; $u.RadiusUsername | Should-NotBe '' }
                if ($u.IdentityProvider) { $idps | Should-ContainCollection $u.IdentityProvider; $u.UserAuthType | Should-Be 'idp'; $u.IdpUserId | Should-NotBe '' }
                if ($u.UserAuthType -eq 'radius') { $u.RadiusProxy | Should-NotBe '' }
                if ($u.UserAuthType -eq 'idp') { $u.IdentityProvider | Should-NotBe '' }
            }
            @($script:Users | Where-Object RadiusProxy).Username | Should-BeCollection @('praghunathan')
            @($script:Users | Where-Object IdentityProvider).Username | Should-BeCollection @('ofitzgerald')
            # One proxy and one provider are linked to by nobody, on purpose.
            @($proxies | Where-Object { $script:Users.RadiusProxy -notcontains $_ }) | Should-BeCollection @('decommissioned-radius')
            @($idps | Where-Object { $script:Users.IdentityProvider -notcontains $_ }) | Should-BeCollection @('keycloak-pilot')
        }

        It 'has an OTP-only user with a token, and one without' {
            $otpUsers = @($script:Users | Where-Object UserAuthType -eq 'otp' | ForEach-Object { $_.Username })
            $otpUsers.Count | Should-Be 2
            $owners = @($script:OtpTokens.Owner)
            @($otpUsers | Where-Object { $owners -contains $_ }) | Should-BeCollection @('jnino')
            @($otpUsers | Where-Object { $owners -notcontains $_ }) | Should-BeCollection @('hkobayashi')
        }

        It 'has exactly one active user whose principal has already expired' {
            $expired = @($script:Users | Where-Object { $_.PrincipalExpiresInDays -match '^-\d+$' })
            $expired.Username | Should-BeCollection @('ofitzgerald')
            $expired[0].Lifecycle | Should-Be 'Active'
            @($script:Users | Where-Object { $_.PrincipalExpiresInDays -and $_.PrincipalExpiresInDays -notmatch '^-?\d+$' }) | Should-BeCollection -Count 0
        }

        It 'gives the user with no private group a POSIX primary group that exists, and nobody else one' {
            foreach ($u in $script:Users) {
                if ($u.NoPrivateGroup -eq 'TRUE') {
                    ($script:Groups | Where-Object Name -eq $u.PrimaryGroup).Type | Should-Be 'posix'
                }
                else {
                    $u.PrimaryGroup | Should-Be ''
                }
            }
            @($script:Users | Where-Object NoPrivateGroup -eq 'TRUE').Count | Should-Be 1
        }

        It 'carries public keys that parse, and two on one user' {
            $withKeys = @($script:Users | Where-Object SshPublicKeys)
            $withKeys.Count | Should-BeGreaterThan 1
            foreach ($u in $withKeys) {
                foreach ($key in (& $script:Split $u.SshPublicKeys)) {
                    $parts = $key -split ' '
                    $parts[0] | Should-MatchString '^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp256)$'
                    # A key that does not decode throws here, which fails the test.
                    ([Convert]::FromBase64String($parts[1])).Length | Should-BeGreaterThan 0
                }
            }
            @($withKeys | Where-Object { (& $script:Split $_.SshPublicKeys).Count -eq 2 }).Username | Should-BeCollection @('zmueller')
        }

        It 'gives one user certificate mapping data that the smart-card mapping rule would match' {
            $mapped = @($script:Users | Where-Object CertMapData)
            $mapped.Username | Should-BeCollection @('awhitfield')
            $issuer, $subject = $mapped[0].CertMapData -split '\|'
            $subject | Should-MatchString '^CN='
            $rule = $script:CertMapRules | Where-Object Name -eq 'lab-smartcard'
            $rule.Enabled | Should-Be 'TRUE'
            $rule.MatchRule | Should-Be "<ISSUER>$issuer"
        }

        It 'uses absolute shells, a language tag or nothing, and a home only where it is not the default' {
            @($script:Users | Where-Object { $_.LoginShell -notmatch '^/' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.PreferredLanguage -and $_.PreferredLanguage -notmatch '^[a-z]{2}-[A-Z]{2}$' }) | Should-BeCollection -Count 0
            @($script:Users | Where-Object { $_.HomeDirectory -and $_.HomeDirectory -eq "/home/$($_.Username)" }) | Should-BeCollection -Count 0
        }

        It 'keeps the accented names intact through a UTF-8 read, in each tier' {
            @($script:Users | Where-Object { $_.Tier -eq 'Core' -and $_.DisplayName -match '[^\x00-\x7F]' }).Count | Should-BeGreaterThan 2
            @($script:Users | Where-Object { $_.Tier -eq 'Bulk' -and $_.DisplayName -match '[^\x00-\x7F]' }).Count | Should-BeGreaterThan 2
        }
    }

    Context 'Member managers' {
        It 'names only seeded users and groups as managers, on a few core groups and host groups, and never on the bulk' {
            foreach ($set in @($script:Groups), @($script:Hostgroups)) {
                @($set | ForEach-Object { & $script:Split $_.ManagerUsers } | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @($set | ForEach-Object { & $script:Split $_.ManagerGroups } | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @($set | Where-Object { $_.Tier -eq 'Bulk' -and ($_.ManagerUsers -or $_.ManagerGroups) }) | Should-BeCollection -Count 0
            }
            @($script:Groups | Where-Object { $_.ManagerUsers -or $_.ManagerGroups }).Name | Should-BeCollection @('dept-engineering', 'team-platform', 'contractors')
            @($script:Hostgroups | Where-Object { $_.ManagerUsers -or $_.ManagerGroups }).Name | Should-BeCollection @('web-servers', 'bastions')
        }
    }

    Context 'Identity providers' {
        It 'has two proxies and two providers of the kinds FreeIPA has templates for, pointed at the seed zone or nowhere' {
            @($script:IdentityProviders | Where-Object Kind -eq 'Radius').Count | Should-Be 2
            @($script:IdentityProviders | Where-Object Kind -eq 'Idp').Count | Should-Be 2
            foreach ($p in $script:IdentityProviders) {
                $p.Kind | Should-MatchString '^(Radius|Idp)$'
                if ($p.Kind -eq 'Radius') {
                    $p.Server | Should-MatchString ':\d+$'
                    $p.Timeout | Should-MatchString '^\d+$'
                    $p.Retries | Should-MatchString '^\d+$'
                    $p.Provider | Should-Be ''
                }
                else {
                    $p.Provider | Should-MatchString '^(google|github|microsoft|okta|keycloak)$'
                    $p.ClientId | Should-MatchString '^\{prefix\}'
                    $p.Description | Should-Be ''
                    if ($p.Provider -in 'keycloak', 'okta') { $p.BaseUrl | Should-NotBe '' } else { $p.BaseUrl | Should-Be '' }
                }
            }
            ($script:IdentityProviders | Where-Object Name -eq 'legacy-radius').Server | Should-MatchString '^\{prefix\}legacy01\.\{zone\}:'
            ($script:IdentityProviders | Where-Object Name -eq 'decommissioned-radius').Server | Should-MatchString '\.invalid:'
        }
    }

    Context 'Hosts and host groups' {
        BeforeAll {
            $script:HostgroupParentsOf = @{}
            foreach ($hg in $script:Hostgroups) { $script:HostgroupParentsOf[$hg.Name] = @(& $script:Split $hg.Parent) }
        }

        It 'names only host groups that exist, on hosts and as parents, and never nests across tiers' {
            @($script:Hosts | ForEach-Object { & $script:Split $_.Hostgroups } | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
            @($script:Hostgroups | ForEach-Object { $script:HostgroupParentsOf[$_.Name] } | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
            $tierOf = @{}
            foreach ($hg in $script:Hostgroups) { $tierOf[$hg.Name] = $hg.Tier }
            @($script:Hostgroups | Where-Object { $row = $_; @($script:HostgroupParentsOf[$row.Name] | Where-Object { $tierOf[$_] -ne $row.Tier }).Count -gt 0 }) | Should-BeCollection -Count 0
        }

        It 'nests the core servers two deep, with one host a direct member of the root' {
            $script:HostgroupParentsOf['web-servers'] | Should-BeCollection @('all-servers')
            @($script:Hosts | Where-Object { (& $script:Split $_.Hostgroups) -contains 'all-servers' }).Name | Should-BeCollection @('nfs01')
        }

        It 'leaves exactly the designed host groups with no host of their own' {
            $direct = @($script:Hosts | ForEach-Object { & $script:Split $_.Hostgroups } | Sort-Object -Unique)
            @($script:Hostgroups | Where-Object { $direct -notcontains $_.Name } | ForEach-Object { $_.Name } | Sort-Object) | Should-BeCollection @('empty-hostgroup', 'servers')
        }

        It 'has one host with nothing at all: no description, no OS, no group, no address' {
            @($script:Hosts | Where-Object { -not $_.Description -and -not $_.OperatingSystem -and -not $_.Hostgroups }).Name | Should-BeCollection @('orphan01')
            @($script:Hosts | Where-Object { -not $_.IPAddress }).Name | Should-BeCollection @('orphan01')
        }

        It 'gives every other host its own address inside the seed subnet, by office' {
            # The reverse zone the seed creates covers 10.213.0.0/16 and nothing else, so an
            # address outside it would have no PTR; a duplicate would collide on one.
            $addressed = @($script:Hosts | Where-Object IPAddress)
            @($addressed | Where-Object { $_.IPAddress -notmatch '^10\.213\.\d{1,3}\.\d{1,3}$' }) | Should-BeCollection -Count 0
            @($addressed | ForEach-Object { [ipaddress]$_.IPAddress }) | Should-BeCollection -Count $addressed.Count
            @($addressed.IPAddress | Sort-Object -Unique).Count | Should-Be $addressed.Count
            # The core sits in 10.213.0.0/24 with the Zürich kiosk on its own; the bulk starts at .10.
            @($script:Hosts | Where-Object { $_.Tier -eq 'Core' -and $_.IPAddress -like '10.213.0.*' }).Count | Should-Be 6
            ($script:Hosts | Where-Object Name -eq 'kiosk01').IPAddress | Should-Be '10.213.9.20'
            @($script:Hosts | Where-Object { $_.Tier -eq 'Bulk' -and [int](($_.IPAddress -split '\.')[2]) -lt 10 }) | Should-BeCollection -Count 0
            # Hosts at one office share a /24 (or spill into the next).
            $bySite = @($script:Hosts | Where-Object Tier -eq 'Bulk') | Group-Object { @(& $script:Split $_.Hostgroups | Where-Object { $_ -like 'site-*' })[0] }
            foreach ($site in $bySite) {
                @($site.Group | ForEach-Object { [int](($_.IPAddress -split '\.')[2]) } | Sort-Object -Unique).Count | Should-BeLessThanOrEqual 2
            }
            # No address the extra records use belongs to a host.
            $recordAddresses = @($script:DnsRecords | Where-Object Type -eq 'A' | ForEach-Object { & $script:Split $_.Data })
            @($addressed | Where-Object { $recordAddresses -contains $_.IPAddress }) | Should-BeCollection -Count 0
        }

        It 'names only hosts that exist as managers, and uses values FreeIPA validates' {
            @($script:Hosts | Where-Object { $_.ManagedBy -and ($script:Hosts.Name -notcontains $_.ManagedBy) }) | Should-BeCollection -Count 0
            @($script:Hosts | Where-Object { $_.MacAddress -and $_.MacAddress -notmatch '^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$' }) | Should-BeCollection -Count 0
            @($script:Hosts | Where-Object { $_.AuthIndicator -and $_.AuthIndicator -notin 'radius', 'otp', 'pkinit', 'hardened', 'idp', 'passkey' }) | Should-BeCollection -Count 0
            @($script:Hosts | Where-Object AuthIndicator).Name | Should-BeCollection @('bastion01')
            @($script:Hosts | Where-Object SshPublicKey).Name | Should-BeCollection @('web01')
        }

        It 'brings across only the devices that could enrol, each in a kind group and a site group' {
            $kinds = @('workstation', 'file-server', 'database-server', 'mail-server', 'domain-controller')
            $bulk = @($script:Hosts | Where-Object Tier -eq 'Bulk')
            @($bulk | Where-Object { $_.Class -notin $kinds }) | Should-BeCollection -Count 0
            @($bulk | Where-Object { @(& $script:Split $_.Hostgroups | Where-Object { $_ -like 'site-*' }).Count -ne 1 }) | Should-BeCollection -Count 0
            @($bulk | Where-Object { @(& $script:Split $_.Hostgroups | Where-Object { $_ -notlike 'site-*' }).Count -ne 1 }) | Should-BeCollection -Count 0
        }
    }

    Context 'Automember rules' {
        It 'targets a group or host group that exists, of the kind it says' {
            foreach ($rule in $script:AutomemberRules) {
                $rule.Kind | Should-MatchString '^(group|hostgroup)$'
                $set = if ($rule.Kind -eq 'group') { $script:Groups } else { $script:Hostgroups }
                @($set | Where-Object Name -eq $rule.Target).Count | Should-Be 1
                foreach ($condition in (& $script:Split $rule.Conditions)) { $condition | Should-MatchString '^!?[a-z]+=.+$' }
            }
        }

        It 'agrees with the membership the data already lists, so a rebuild changes nothing' {
            # An automember rule fires as entries are created. If the rows disagreed with the
            # rule the live directory would differ from the CSV and every membership test here
            # would be proving the wrong thing.
            $in = { param($row, $column, $key) (& $script:Split $row.$column) -contains $key }
            @($script:Users | Where-Object { ($_.EmployeeType -eq 'Contractor') -ne (& $in $_ 'Groups' 'contractors') }) | Should-BeCollection -Count 0
            @($script:Hosts | Where-Object { ($_.Class -eq 'workstation') -ne (& $in $_ 'Hostgroups' 'workstations') }) | Should-BeCollection -Count 0
            @($script:Hosts | Where-Object { ($_.OperatingSystem -match '^CentOS') -ne (& $in $_ 'Hostgroups' 'legacy-hosts') }) | Should-BeCollection -Count 0
            @($script:Hosts | Where-Object { ($_.Locality -match '^Zurich') -ne (& $in $_ 'Hostgroups' 'site-zurich-hosts') }) | Should-BeCollection -Count 0
            ($script:AutomemberRules | Where-Object Target -eq 'empty-hold').Conditions | Should-MatchString '^!'
        }
    }

    Context 'Netgroups' {
        It 'names only members that exist, nests one netgroup in another, and leaves one empty' {
            foreach ($n in $script:Netgroups) {
                @(& $script:Split $n.Users | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $n.Groups | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $n.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $n.Hostgroups | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $n.Netgroups | Where-Object { $script:Netgroups.Name -notcontains $_ -or $_ -eq $n.Name }) | Should-BeCollection -Count 0
                @($n.UserCategory, $n.HostCategory | Where-Object { $_ -and $_ -ne 'all' }) | Should-BeCollection -Count 0
            }
            @($script:Netgroups | Where-Object Netgroups).Count | Should-Be 1
            @($script:Netgroups | Where-Object { -not ($_.Users + $_.Groups + $_.Hosts + $_.Hostgroups + $_.Netgroups) }).Name | Should-BeCollection @('empty-net')
        }
    }

    Context 'HBAC' {
        It 'has services and service groups whose members are seeded services or allowed stock ones' {
            @($script:HbacServices | Where-Object { $_.Kind -notin 'Service', 'Group' }) | Should-BeCollection -Count 0
            $services = @($script:HbacServices | Where-Object Kind -eq 'Service' | ForEach-Object { $_.Name })
            foreach ($g in ($script:HbacServices | Where-Object Kind -eq 'Group')) {
                @(& $script:Seeded $g.Members | Where-Object { $services -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Builtin $g.Members | Where-Object { $script:AllowedBuiltinServices -notcontains $_ }) | Should-BeCollection -Count 0
            }
            @($script:HbacServices | Where-Object Kind -eq 'Service' | Where-Object Members) | Should-BeCollection -Count 0
        }

        It 'resolves every rule member, and uses a category only with no members of that kind' {
            $services = @($script:HbacServices | Where-Object Kind -eq 'Service' | ForEach-Object { $_.Name })
            $serviceGroups = @($script:HbacServices | Where-Object Kind -eq 'Group' | ForEach-Object { $_.Name })
            foreach ($r in $script:HbacRules) {
                $r.Enabled | Should-MatchString '^(TRUE|FALSE)$'
                @(& $script:Split $r.Users | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Groups | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Hostgroups | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Seeded $r.Services | Where-Object { $services -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Builtin $r.Services | Where-Object { $script:AllowedBuiltinServices -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.ServiceGroups | Where-Object { $serviceGroups -notcontains $_ }) | Should-BeCollection -Count 0
                foreach ($category in 'UserCategory', 'HostCategory', 'ServiceCategory') { @($r.$category | Where-Object { $_ -and $_ -ne 'all' }) | Should-BeCollection -Count 0 }
                if ($r.UserCategory) { ($r.Users + $r.Groups) | Should-Be '' }
                if ($r.HostCategory) { ($r.Hosts + $r.Hostgroups) | Should-Be '' }
                if ($r.ServiceCategory) { ($r.Services + $r.ServiceGroups) | Should-Be '' }
            }
        }

        It 'has the allow-everything rule switched off, one empty rule, a double grant and a disabled user still named' {
            $open = $script:HbacRules | Where-Object { $_.UserCategory -eq 'all' -and $_.HostCategory -eq 'all' -and $_.ServiceCategory -eq 'all' }
            @($open).Count | Should-Be 1
            $open.Enabled | Should-Be 'FALSE'
            @($script:HbacRules | Where-Object { $_.Enabled -eq 'TRUE' -and -not ($_.Users + $_.Groups + $_.Hosts + $_.Hostgroups + $_.Services + $_.ServiceGroups + $_.UserCategory + $_.HostCategory + $_.ServiceCategory) }).Name | Should-BeCollection @('unbound')
            $payroll = $script:HbacRules | Where-Object Name -eq 'finance-payroll'
            $payroll.Users | Should-Be 'praghunathan'
            $payroll.Groups | Should-Be 'dept-finance'
            $disabled = @($script:Users | Where-Object Lifecycle -eq 'Disabled' | ForEach-Object { $_.Username })
            @($script:HbacRules | Where-Object { $_.Enabled -eq 'TRUE' -and (& $script:Split $_.Users | Where-Object { $disabled -contains $_ }).Count -gt 0 }).Count | Should-BeGreaterThan 0
        }
    }

    Context 'Sudo' {
        It 'names commands by path, groups them only from seeded commands, and leaves one group empty' {
            $commands = @($script:SudoCommands | Where-Object Kind -eq 'Command')
            @($commands | Where-Object { $_.Name -notmatch '^/' -or $_.Members }) | Should-BeCollection -Count 0
            foreach ($g in ($script:SudoCommands | Where-Object Kind -eq 'Group')) {
                $g.Name | Should-MatchString $script:NamePattern
                @(& $script:Split $g.Members | Where-Object { $commands.Name -notcontains $_ }) | Should-BeCollection -Count 0
            }
            @($script:SudoCommands | Where-Object { $_.Kind -eq 'Group' -and -not $_.Members }).Name | Should-BeCollection @('empty-cmdgroup')
        }

        It 'resolves every rule member, orders the rules uniquely, and runs only as seeded or local accounts' {
            $commands = @($script:SudoCommands | Where-Object Kind -eq 'Command' | ForEach-Object { $_.Name })
            $groups = @($script:SudoCommands | Where-Object Kind -eq 'Group' | ForEach-Object { $_.Name })
            $localAccounts = @('root', 'postgres', 'nobody')
            foreach ($r in $script:SudoRules) {
                $r.Enabled | Should-MatchString '^(TRUE|FALSE)$'
                $r.Order | Should-MatchString '^\d+$'
                @(& $script:Split $r.Users | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Groups | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Hostgroups | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.AllowCommands | Where-Object { $commands -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.DenyCommands | Where-Object { $commands -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.AllowCommandGroups | Where-Object { $groups -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.RunAsUsers | Where-Object { $script:Users.Username -notcontains $_ -and $localAccounts -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Options | Where-Object { $_ -notin '!authenticate', '!requiretty', 'env_keep+=SSH_AUTH_SOCK' }) | Should-BeCollection -Count 0
                foreach ($category in 'UserCategory', 'HostCategory', 'CommandCategory', 'RunAsUserCategory') { @($r.$category | Where-Object { $_ -and $_ -ne 'all' }) | Should-BeCollection -Count 0 }
                if ($r.CommandCategory) { ($r.AllowCommands + $r.AllowCommandGroups) | Should-Be '' }
            }
            @($script:SudoRules.Order | Sort-Object -Unique).Count | Should-Be $script:SudoRules.Count
        }

        It 'keeps the findings a sudo review exists for: a disabled rule for a disabled user, a shell escape without a password, and an empty rule' {
            $legacy = $script:SudoRules | Where-Object Name -eq 'legacy-root-shell'
            $legacy.Enabled | Should-Be 'FALSE'
            ($script:Users | Where-Object Username -eq $legacy.Users).Lifecycle | Should-Be 'Disabled'
            $escape = $script:SudoRules | Where-Object Name -eq 'contractor-editors'
            $escape.Options | Should-MatchString '!authenticate'
            (& $script:Split ($script:SudoCommands | Where-Object Name -eq $escape.AllowCommandGroups).Members) | Should-ContainCollection '/usr/bin/vim'
            @($script:SudoRules | Where-Object { -not ($_.Users + $_.Groups + $_.Hosts + $_.Hostgroups + $_.AllowCommands + $_.AllowCommandGroups + $_.DenyCommands + $_.UserCategory + $_.HostCategory + $_.CommandCategory) }).Name | Should-BeCollection @('empty-sudo')
        }
    }

    Context 'RBAC' {
        It 'chains roles to privileges to permissions, with stock privileges only from the read-only list' {
            foreach ($p in $script:Privileges) {
                @(& $script:Split $p.Permissions | Where-Object { $script:Permissions.Name -notcontains $_ }) | Should-BeCollection -Count 0
            }
            foreach ($r in $script:Roles) {
                @(& $script:Seeded $r.Privileges | Where-Object { $script:Privileges.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Builtin $r.Privileges | Where-Object { $script:AllowedBuiltinPrivileges -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Users | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Groups | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $r.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
            }
            @($script:Roles | Where-Object { -not ($_.Users + $_.Groups + $_.Hosts) }).Name | Should-BeCollection @('empty-role')
            @($script:Roles | Where-Object Hosts).Count | Should-Be 1
        }

        It 'scopes every permission that writes to the seed tag, and grants nothing beyond read and write' {
            foreach ($p in $script:Permissions) {
                @(& $script:Split $p.Rights | Where-Object { $_ -notin 'read', 'search', 'compare', 'write' }) | Should-BeCollection -Count 0
                $p.Type | Should-MatchString '^(user|group|host|hostgroup|sudorule|hbacrule)$'
                if ((& $script:Split $p.Rights) -contains 'write') { $p.Filter | Should-MatchString '\{tag\}' }
            }
            @($script:Permissions | Where-Object { $_.Filter -and $_.Filter -notmatch '^\(userclass=\{tag\}\)$' }) | Should-BeCollection -Count 0
        }

        It 'never puts a seeded member in a stock role or group' {
            # The data references stock privileges through builtin: only. A stock group or
            # role as a membership target would mean the seed writes to it.
            $targets = @($script:Users | ForEach-Object { & $script:Split $_.Groups }) + @($script:Groups | ForEach-Object { & $script:Split $_.Parent }) + @($script:Roles.Name)
            @($targets | Where-Object { $script:StockNames -contains $_.ToLowerInvariant() }) | Should-BeCollection -Count 0
        }
    }

    Context 'Password policies' {
        It 'attaches only to seeded groups, once each, with distinct priorities, and never to the global policy' {
            @($script:PasswordPolicies | Where-Object { $script:Groups.Name -notcontains $_.Group }) | Should-BeCollection -Count 0
            @($script:PasswordPolicies.Group | Sort-Object -Unique).Count | Should-Be $script:PasswordPolicies.Count
            @($script:PasswordPolicies.Priority | Sort-Object -Unique).Count | Should-Be $script:PasswordPolicies.Count
            foreach ($p in $script:PasswordPolicies) {
                foreach ($column in 'Priority', 'MaxLife', 'MinLife', 'History', 'MinClasses', 'MinLength', 'MaxFail', 'FailInterval', 'LockoutTime') { $p.$column | Should-MatchString '^\d+$' }
                $p.GraceLimit | Should-MatchString '^-?\d+$'
            }
        }

        It 'has one policy that never expires a password and never locks out' {
            @($script:PasswordPolicies | Where-Object { $_.MaxLife -eq '0' -and $_.MaxFail -eq '0' }).Group | Should-BeCollection @('dept-sales')
        }
    }

    Context 'Services and delegation' {
        It 'places every service on a seeded host, managed only by a seeded host' {
            foreach ($s in $script:Services) {
                $s.Principal | Should-MatchString '^[A-Za-z]+/[a-z0-9-]+$'
                $script:Hosts.Name | Should-ContainCollection ($s.Principal -split '/')[1]
                @(& $script:Split $s.ManagedBy | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $s.AuthIndicators | Where-Object { $_ -notin 'radius', 'otp', 'pkinit', 'hardened', 'idp', 'passkey' }) | Should-BeCollection -Count 0
            }
            @($script:Services.Principal | Sort-Object -Unique).Count | Should-Be $script:Services.Count
        }

        It 'delegates only between seeded services, and has one target with no members' {
            $targets = @($script:ServiceDelegation | Where-Object Kind -eq 'Target')
            $rules = @($script:ServiceDelegation | Where-Object Kind -eq 'Rule')
            ($targets.Count + $rules.Count) | Should-Be $script:ServiceDelegation.Count
            foreach ($d in $script:ServiceDelegation) {
                @(& $script:Split $d.Members | Where-Object { $script:Services.Principal -notcontains $_ }) | Should-BeCollection -Count 0
            }
            foreach ($r in $rules) {
                @(& $script:Split $r.Targets | Where-Object { $targets.Name -notcontains $_ }) | Should-BeCollection -Count 0
                $r.Members | Should-NotBe ''
            }
            @($targets | Where-Object { -not $_.Members }).Name | Should-BeCollection @('empty-target')
            @($targets | Where-Object Targets) | Should-BeCollection -Count 0
        }
    }

    Context 'ID views' {
        It 'overrides only seeded users and groups in views that exist, and applies views only to seeded hosts' {
            foreach ($o in $script:IdOverrides) {
                $script:IdViews.Name | Should-ContainCollection $o.View
                $o.Kind | Should-MatchString '^(User|Group)$'
                $set = if ($o.Kind -eq 'User') { $script:Users.Username } else { $script:Groups.Name }
                $set | Should-ContainCollection $o.Anchor
                foreach ($column in 'Uid', 'Gid') { if ($o.$column) { $o.$column | Should-MatchString '^\d+$' } }
                if ($o.Login) { $o.Login | Should-MatchString $script:NamePattern }
            }
            foreach ($v in $script:IdViews) {
                @(& $script:Split $v.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $v.Hostgroups | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
            }
        }

        It 'has one view applied nowhere that still holds an override, and never overrides an anchor twice in one view' {
            $unapplied = @($script:IdViews | Where-Object { -not ($_.Hosts + $_.Hostgroups) })
            $unapplied.Name | Should-BeCollection @('unapplied-view')
            @($script:IdOverrides | Where-Object View -eq 'unapplied-view').Count | Should-BeGreaterThan 0
            @($script:IdOverrides | ForEach-Object { "$($_.View)/$($_.Kind)/$($_.Anchor)" } | Sort-Object -Unique).Count | Should-Be $script:IdOverrides.Count
        }
    }

    Context 'OTP tokens' {
        It 'belongs to seeded users, one disabled, one expired, and uses only what FreeIPA accepts' {
            @($script:OtpTokens | Where-Object { $script:Users.Username -notcontains $_.Owner }) | Should-BeCollection -Count 0
            foreach ($t in $script:OtpTokens) {
                $t.Type | Should-MatchString '^(totp|hotp)$'
                $t.Enabled | Should-MatchString '^(TRUE|FALSE)$'
                $t.Algorithm | Should-MatchString '^sha(1|256|384|512)$'
                $t.Digits | Should-MatchString '^(6|8)$'
                if ($t.ExpiresInDays) { $t.ExpiresInDays | Should-MatchString '^-?\d+$' }
            }
            @($script:OtpTokens | Where-Object Enabled -eq 'FALSE').Owner | Should-BeCollection @('talvarez')
            @($script:OtpTokens | Where-Object { $_.ExpiresInDays -match '^-' }).Id | Should-BeCollection @('mbell-expired')
            @($script:OtpTokens | Where-Object Type -eq 'hotp').Count | Should-Be 1
        }
    }

    Context 'Automount' {
        It 'has two locations, the second with a map of the same name as the first pointing at a server the realm does not know' {
            @($script:Automount | Where-Object Kind -eq 'Location').Location | Should-BeCollection @('lab', 'branch')
            @($script:Automount | Where-Object { $_.Kind -eq 'Map' -and $_.Map -eq 'auto.home' }).Location | Should-BeCollection @('lab', 'branch')
            ($script:Automount | Where-Object { $_.Location -eq 'branch' -and $_.Kind -eq 'Key' }).Info | Should-MatchString 'nfs02'
            $script:Hosts.Name | Should-NotContainCollection @('nfs02')
        }

        It 'keeps every map and key in a seeded location, and keys in seeded maps or the ones FreeIPA creates with the location' {
            $locations = @($script:Automount | Where-Object Kind -eq 'Location').Location
            @($script:Automount | Where-Object { $locations -notcontains $_.Location }) | Should-BeCollection -Count 0
            $maps = @($script:Automount | Where-Object Kind -eq 'Map')
            @($maps | Where-Object { -not $_.MountPoint -or $_.MountPoint -notmatch '^/' }) | Should-BeCollection -Count 0
            foreach ($k in ($script:Automount | Where-Object Kind -eq 'Key')) {
                (@($maps | Where-Object Location -eq $k.Location | ForEach-Object { $_.Map }) + @('auto.master', 'auto.direct')) | Should-ContainCollection $k.Map
                $k.Info | Should-MatchString '\{prefix\}nfs0[12]\.ipalab\.example\.com:'
            }
            @($script:Automount | Where-Object { $_.Kind -eq 'Key' -and $_.Map -eq 'auto.direct' }).Count | Should-Be 1
        }
    }

    Context 'SELinux user maps' {
        It 'uses SELinux users from the stock order, scopes by a rule or by members but never both, and resolves every member' {
            $order = @('guest_u:s0', 'xguest_u:s0', 'user_u:s0', 'staff_u:s0-s0:c0.c1023', 'sysadm_u:s0-s0:c0.c1023', 'unconfined_u:s0-s0:c0.c1023')
            foreach ($m in $script:SelinuxUserMaps) {
                $order | Should-ContainCollection $m.SelinuxUser
                $m.Enabled | Should-MatchString '^(TRUE|FALSE)$'
                $members = $m.Users + $m.Groups + $m.Hosts + $m.Hostgroups
                if ($m.HbacRule) {
                    $script:HbacRules.Name | Should-ContainCollection $m.HbacRule
                    $members | Should-Be ''
                }
                else {
                    $members | Should-NotBe ''
                }
                @(& $script:Split $m.Users | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $m.Groups | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $m.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $m.Hostgroups | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
            }
            @($script:SelinuxUserMaps | Where-Object Enabled -eq 'FALSE').Count | Should-Be 1
        }
    }

    Context 'Certificate mapping rules' {
        It 'has two enabled rules and one disabled, each with a match and a map, the email one on the seed domain and the realm one on the realm' {
            @($script:CertMapRules | Where-Object Enabled -eq 'TRUE').Count | Should-Be 2
            @($script:CertMapRules | Where-Object Enabled -eq 'FALSE').Count | Should-Be 1
            ($script:CertMapRules | Where-Object Name -eq 'realm-ca').MatchRule | Should-MatchString 'O=\{realm\}$'
            ($script:CertMapRules | Where-Object Name -eq 'realm-ca').MapRule | Should-Be '(userCertificate;binary={cert!bin})'
            foreach ($r in $script:CertMapRules) {
                $r.MatchRule | Should-MatchString '^<'
                $r.MapRule | Should-MatchString '^\('
                $r.Priority | Should-MatchString '^\d+$'
            }
            ($script:CertMapRules | Where-Object Name -eq 'legacy-email-match').MatchRule | Should-MatchString 'ipalab\\\.example\\\.com'
        }
    }

    Context 'DNS records' {
        It 'puts every record in one of the two seed zones, in a type the step can send, and names seeded hosts or the deliberately stale ones' {
            foreach ($r in $script:DnsRecords) {
                $r.Zone | Should-MatchString '^(Forward|Reverse)$'
                $r.Type | Should-MatchString '^(A|CNAME|MX|TXT|SRV|PTR)$'
                $r.Name | Should-NotBe ''
                $r.Data | Should-NotBe ''
                if ($r.Type -eq 'PTR') { $r.Zone | Should-Be 'Reverse' } else { $r.Zone | Should-Be 'Forward' }
                # A name written against the zone carries the placeholder, never a literal domain.
                foreach ($value in (& $script:Split $r.Data)) {
                    if ($value -match '\.$') { $value | Should-MatchString '\{zone\}\.$' }
                }
            }
            # The aliases and the mail exchanger point at seeded hosts, except the one stale
            # alias and the one ghost reverse record, which is the point of them.
            $targets = @($script:DnsRecords | Where-Object { $_.Type -in 'CNAME', 'MX', 'SRV', 'PTR' } | ForEach-Object { & $script:Split $_.Data } | ForEach-Object { ($_ -split ' ')[-1] })
            $hostOf = { param($target) if ($target -match '^\{prefix\}([a-z0-9-]+)\.\{zone\}\.$') { $Matches[1] } else { $target } }
            $named = @($targets | ForEach-Object { & $hostOf $_ })
            @($named | Where-Object { $script:Hosts.Name -notcontains $_ } | Sort-Object -Unique) | Should-BeCollection @('ghost01.{zone}.', 'oldweb01', 'decommissioned01')
            @($script:DnsRecords | Where-Object { $_.Type -eq 'A' -and $_.Name -eq 'lb' } | ForEach-Object { & $script:Split $_.Data }).Count | Should-Be 2
            @($script:DnsRecords | Where-Object { $_.Name -eq '@' }).Type | Should-BeCollection @('MX', 'TXT')
        }
    }

    Context 'CA ACLs and certificates' {
        It 'names only seeded members and builtin profiles and CAs, has one disabled rule and one that matches nothing' {
            foreach ($a in $script:CaAcls) {
                @(& $script:Split $a.Users | Where-Object { $script:Users.Username -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $a.Groups | Where-Object { $script:Groups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $a.Hosts | Where-Object { $script:Hosts.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $a.Hostgroups | Where-Object { $script:Hostgroups.Name -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Split $a.Services | Where-Object { $script:Services.Principal -notcontains $_ }) | Should-BeCollection -Count 0
                # A profile or a CA is only ever a stock object, and only from the short list.
                @(& $script:Seeded $a.Profiles) | Should-BeCollection -Count 0
                @(& $script:Builtin $a.Profiles | Where-Object { $script:AllowedBuiltinProfiles -notcontains $_ }) | Should-BeCollection -Count 0
                @(& $script:Seeded $a.Cas) | Should-BeCollection -Count 0
                @(& $script:Builtin $a.Cas | Where-Object { $script:AllowedBuiltinCas -notcontains $_ }) | Should-BeCollection -Count 0
                foreach ($category in 'UserCategory', 'HostCategory', 'ServiceCategory', 'ProfileCategory', 'CaCategory') {
                    $a.$category | Should-MatchString '^(all)?$'
                }
            }
            @($script:CaAcls | Where-Object Enabled -eq 'FALSE').Name | Should-BeCollection @('smartcard-pilot')
            $empty = $script:CaAcls | Where-Object Name -eq 'empty-acl'
            ($empty.Users + $empty.Groups + $empty.Hosts + $empty.Hostgroups + $empty.Services) | Should-Be ''
            # No user category of all: a rule that granted every user a certificate would
            # be a change to the realm, not a shape.
            @($script:CaAcls | Where-Object UserCategory -eq 'all') | Should-BeCollection -Count 0
        }

        It 'issues only to seeded principals a CA ACL covers, through builtin profiles, with the states a report must tell apart' {
            $covered = @($script:CaAcls | Where-Object { $_.Enabled -eq 'TRUE' -and (& $script:Builtin $_.Profiles) -contains 'IECUserRoles' })
            $coveredUsers = @($covered | ForEach-Object { & $script:Split $_.Users })
            $coveredGroups = @($covered | ForEach-Object { & $script:Split $_.Groups })
            foreach ($c in $script:Certificates) {
                $c.Kind | Should-MatchString '^(User|Service|Host)$'
                $c.State | Should-MatchString '^(Valid|Revoked)$'
                @(& $script:Seeded $c.Profile) | Should-BeCollection -Count 0
                @(& $script:Builtin $c.Profile | Where-Object { $script:AllowedBuiltinProfiles -notcontains $_ }) | Should-BeCollection -Count 0
                switch ($c.Kind) {
                    'User' {
                        $script:Users.Username | Should-ContainCollection $c.Principal
                        $user = $script:Users | Where-Object Username -eq $c.Principal
                        # Active or disabled: a staged or preserved user has no principal to issue to.
                        $user.Lifecycle | Should-MatchString '^(Active|Disabled)$'
                        $inAcl = ($coveredUsers -contains $c.Principal) -or (@(& $script:Split $user.Groups | Where-Object { $coveredGroups -contains $_ }).Count -gt 0)
                        $inAcl | Should-BeTrue
                        @(& $script:Builtin $c.Profile)[0] | Should-Be 'IECUserRoles'
                    }
                    'Service' { $script:Services.Principal | Should-ContainCollection $c.Principal; @(& $script:Builtin $c.Profile)[0] | Should-Be 'caIPAserviceCert' }
                    'Host' { $script:Hosts.Name | Should-ContainCollection $c.Principal; @(& $script:Builtin $c.Profile)[0] | Should-Be 'caIPAserviceCert' }
                }
                if ($c.State -eq 'Revoked') { $c.RevocationReason | Should-MatchString '^(0|1|2|3|4|5|6|8|9|10)$' } else { $c.RevocationReason | Should-Be '' }
                if ($c.SanEmail -eq 'TRUE') { $c.Kind | Should-Be 'User' }
                if ($c.SanDns -eq 'TRUE') { $c.Kind | Should-MatchString '^(Service|Host)$' }
            }
            @($script:Certificates.Key | Sort-Object -Unique).Count | Should-Be $script:Certificates.Count
            # One user carries a revoked certificate beside a valid one; one valid certificate
            # sits on the disabled account; one is on hold; one service one is revoked.
            $zoe = @($script:Certificates | Where-Object Principal -eq 'zmueller')
            @($zoe.State | Sort-Object) | Should-BeCollection @('Revoked', 'Valid')
            ($script:Certificates | Where-Object Principal -eq 'talvarez').State | Should-Be 'Valid'
            ($script:Users | Where-Object Username -eq 'talvarez').Lifecycle | Should-Be 'Disabled'
            @($script:Certificates | Where-Object RevocationReason -eq '6').Count | Should-Be 1
            @($script:Certificates | Where-Object { $_.Kind -eq 'Service' -and $_.State -eq 'Revoked' }).Count | Should-Be 1
            @($script:Certificates | Where-Object Kind -eq 'Host').Count | Should-Be 1
        }
    }

    Context 'Regeneration' {
        It 'reproduces the committed users, groups, hosts and host groups byte for byte' {
            # The bulk tier is generated, and this is what keeps it that way. A hand edit to
            # a generated file is lost the next time the tool runs, so the tool has to agree
            # with the committed file, and a change to the tool has to be committed with
            # its output.
            $tool = Join-Path (Split-Path -Parent $script:DataPath) 'Tools\New-FreeIPATestSeedData.ps1'
            $out = Join-Path $TestDrive 'freeipa-seed'
            $null = New-Item -ItemType Directory -Path $out -Force
            $null = & $tool -OutputPath $out

            foreach ($name in 'FreeIPAUsers', 'FreeIPAGroups', 'FreeIPAHosts', 'FreeIPAHostgroups') {
                $expected = [System.IO.File]::ReadAllBytes((Join-Path $script:DataPath "$name.csv"))
                $actual = [System.IO.File]::ReadAllBytes((Join-Path $out "$name.csv"))
                $actual.Length | Should-Be $expected.Length
                [System.Linq.Enumerable]::SequenceEqual([byte[]]$actual, [byte[]]$expected) | Should-BeTrue
            }
        }
    }
}
